/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author Danny
 */
public class VistaHome extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public VistaHome() {
        initComponents();
        this.setLocationRelativeTo(null);
        
//        UIManager.setLookAndFeel("javax.swing.plaf.metal,MetalLookAndFeel"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/img/FondoDp.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        inicio = new javax.swing.JMenu();
        btnCerrars = new javax.swing.JMenuItem();
        personal = new javax.swing.JMenu();
        btnVistaDocente = new javax.swing.JMenuItem();
        btnVistaEstudiante = new javax.swing.JMenuItem();
        btnVistaAdministrador = new javax.swing.JMenuItem();
        gestion = new javax.swing.JMenu();
        btnVistaCursos = new javax.swing.JMenuItem();
        btnVistaMatriculas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1165, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );

        inicio.setText("Inicio");

        btnCerrars.setText("Cerrar Sesión");
        btnCerrars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarsActionPerformed(evt);
            }
        });
        inicio.add(btnCerrars);

        jMenuBar1.add(inicio);

        personal.setText("Personal");

        btnVistaDocente.setText("Docentes");
        btnVistaDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaDocenteActionPerformed(evt);
            }
        });
        personal.add(btnVistaDocente);

        btnVistaEstudiante.setText("Estudiantes");
        btnVistaEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaEstudianteActionPerformed(evt);
            }
        });
        personal.add(btnVistaEstudiante);

        btnVistaAdministrador.setText("Administrador");
        personal.add(btnVistaAdministrador);

        jMenuBar1.add(personal);

        gestion.setText("Gestion");

        btnVistaCursos.setText("Cursos");
        btnVistaCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaCursosActionPerformed(evt);
            }
        });
        gestion.add(btnVistaCursos);

        btnVistaMatriculas.setText("Matriculas");
        gestion.add(btnVistaMatriculas);

        jMenuBar1.add(gestion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVistaEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaEstudianteActionPerformed
//        VistaEstudiantes e = new VistaEstudiantes();
//        jDesktopPane1.add(e);
//        e.setVisible(true);
//        e.setLocation((jDesktopPane1.getWidth()-e.getWidth())/2, (jDesktopPane1.getHeight()-e.getHeight())/2);
//        e.setSize(690,680); 
    }//GEN-LAST:event_btnVistaEstudianteActionPerformed

    private void btnVistaDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaDocenteActionPerformed
//        Vistadocentes d = new Vistadocentes();
//        jDesktopPane1.add(d);
//        d.setVisible(true);
//        d.setLocation((jDesktopPane1.getWidth()-d.getWidth())/2, (jDesktopPane1.getHeight()-d.getHeight())/2);
//        d.setSize(690,680);
    }//GEN-LAST:event_btnVistaDocenteActionPerformed

    private void btnVistaCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaCursosActionPerformed
//        Cursos c = new Cursos();
//        c.setVisible(true);
//        this.setVisible(false); 
    }//GEN-LAST:event_btnVistaCursosActionPerformed

    private void btnCerrarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarsActionPerformed

    }//GEN-LAST:event_btnCerrarsActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaHome().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem btnCerrars;
    public javax.swing.JMenuItem btnVistaAdministrador;
    public javax.swing.JMenuItem btnVistaCursos;
    public javax.swing.JMenuItem btnVistaDocente;
    public javax.swing.JMenuItem btnVistaEstudiante;
    public javax.swing.JMenuItem btnVistaMatriculas;
    private javax.swing.JMenu gestion;
    private javax.swing.JMenu inicio;
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu personal;
    // End of variables declaration//GEN-END:variables
}
